services:
  api:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - '3333:3333'
    environment:
      PORT: 3333
    depends_on:
      - db
      - envoy
      - oauth2-proxy
      - oidc
