import { Heading, Spinner, Box, Grid, GridItem, Flex } from '@chakra-ui/react';
import {
  DisplacementStatus,
  IdentificationType,
  Sex,
} from '@nrcno/core-models';
import { theme } from '@nrcno/core-theme';

import { EntityList } from '../../components';
import { useEntityListPage } from '../../hooks/useEntityListPage.hook';

export const EntityListPage: React.FC = () => {
  const { entityType, config, isLoading, isError, isSuccess, error, data } =
    useEntityListPage();

  return (
    <Box>
      <Heading
        pb="8"
        bg={theme.colors.white}
        top="0"
        position="sticky"
        zIndex={'docked'}
      >
        {entityType}
      </Heading>
      {isLoading && <Spinner colorScheme="primary" size="xl" />}
      {isError && <div>{error?.message}</div>}
      {isSuccess && <div>Success</div>}
      <EntityList
        config={config}
        entityList={[
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',

            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.AsylumSeeker,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id1',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Female,
          },
          {
            dateOfBirth: new Date('2006-10-12'),
            displacementStatus: DisplacementStatus.HostCommunity,
            email: 'email@email.de',
            firstName: 'first name',
            id: 'id2',
            lastName: 'lastname',
            phone: '21987430219',
            primaryIdentificationNumber: 'kjsdfkjdxf',
            primaryIdentificationType: IdentificationType.NationalId,
            nationality: 'de',
            sex: Sex.Other,
          },
        ]}
      />
    </Box>
  );
};
