name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      BYPASS_AUTHENTICATION: true
      PORT: 3333
      SESSION_SECRET: supersecret
      OIDC_ISSUER: xxx
      OIDC_AUTHORIZATION_URL: xxx
      OIDC_TOKEN_URL: xxx
      OIDC_USER_INFO_URL: xxx
      OIDC_CALLBACK_URL: xxx
      OIDC_SCOPE: xxx
      OIDC_CLIENT_ID: xxx
      OIDC_CLIENT_SECRET: xxx
      OKTA_SCIM_API_TOKEN: xxx
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: core
      TZ: UTC

    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - run: yarn nx-cloud record nx format:check
      - run: yarn nx affected -t lint
      - run: yarn nx affected -t test --exclude=*-e2e
      - run: yarn nx affected -t build
      - run: yarn nx affected -t e2e
